OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_google_sheet_id"
GSPREAD_WORKSHEET_NAME = "Produits"