OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_google_sheet_id"
GSPREAD_WORKSHEET_NAME = "Produits"