OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_google_sheet_id"
GSPREAD_WORKSHEET_NAME = "Produits"