OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_google_sheet_id"
GSPREAD_WORKSHEET_NAME = "Produits"