OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_google_sheet_id"
GSPREAD_WORKSHEET_NAME = "Produits"